"""
Django settings for eurorace project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

environ.Env.read_env(
    BASE_DIR / ".env"
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-gcapc1tbt#tir^sqbun!&5+bekf@q%mt^=vn1$bl^e=bny3%0l"

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["*"])

# Behind nginx reverse proxy under /euroapp (same pattern as pwhub /pwhub)
_force_script_name = env.str("FORCE_SCRIPT_NAME", default="").rstrip("/")
if _force_script_name:
    FORCE_SCRIPT_NAME = _force_script_name
    SESSION_COOKIE_PATH = _force_script_name
    CSRF_COOKIE_PATH = _force_script_name
    # Absolute STATIC/MEDIA URLs do not pick up FORCE_SCRIPT_NAME automatically.
    STATIC_URL = f"{_force_script_name}/static/"
    MEDIA_URL = f"{_force_script_name}/media/"
else:
    STATIC_URL = "/static/"
    MEDIA_URL = "/media/"

USE_X_FORWARDED_HOST = env.bool("USE_X_FORWARDED_HOST", default=bool(_force_script_name))
if USE_X_FORWARDED_HOST:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "corsheaders",  # Dodano obsługę CORS
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.gis",
    "allauth",
    "allauth.socialaccount",
    "allauth.account",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "eurorace",
    "leaflet",
    "rest_framework",
    "rest_framework_gis",
    "rest_framework.authtoken",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "channels"
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Dodano obsługę CORS
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Must wrap CommonMiddleware: APPEND_SLASH returns before inner middleware runs.
    "eurorace.middleware.ForceScriptNameRedirectMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "eurorace.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "eurorace.wsgi.application"
ASGI_APPLICATION = "eurorace.asgi.application"

# Channel layers for WebSocket support
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer" if not DEBUG else "channels.layers.InMemoryChannelLayer",
        "CONFIG": {
            "hosts": [env.str("REDIS_URL", default="redis://localhost:6379/0")],
        } if not DEBUG else {},
    },
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env.str("DB_NAME", default="eurorace"),
        "USER": env.str("DB_USER", default="postgres"),
        "PASSWORD": env.str("DB_PASSWORD", default="postgres"),
        "HOST": env.str("DB_HOST", default="localhost"),
        "PORT": env.str("DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# STATIC_URL / MEDIA_URL are set above (with FORCE_SCRIPT_NAME when deployed under /euroapp).
STATIC_ROOT = BASE_DIR / "static"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# DRF

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# dj-rest-auth settings
REST_AUTH = {
    'USE_JWT': False,
    'SESSION_LOGIN': False,
    'REGISTER_SERIALIZER': 'dj_rest_auth.registration.serializers.RegisterSerializer',
}

# allauth settings
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_USERNAME_REQUIRED = True
SITE_ID = 1

# Ustawienia hasła
ACCOUNT_PASSWORD_MIN_LENGTH = 8
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True


# Email settings
# Zmiana z SMTP na backend konsolowy - emaile będą wyświetlane w konsoli, a nie wysyłane
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Poniższe ustawienia nie są potrzebne dla backendu konsolowego, ale zostawiamy je dla przyszłej konfiguracji
EMAIL_HOST = env.str("EMAIL_HOST", default="localhost")
EMAIL_PORT = env.int("EMAIL_PORT", default=25)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env.str("EMAIL_HOST_USER", default="webmaster@localhost")
# EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)

# Konfiguracja CORS
CORS_ALLOW_ALL_ORIGINS = True

# Optional provider endpoint returning Hitchwiki-compatible nearby spots as JSON.
HITCHWIKI_SPOTS_URL = env.str("HITCHWIKI_SPOTS_URL", default="")

# Admin geo widgets: Leaflet shell + MapLibre GL basemap (Polish labels via OpenFreeMap).
LEAFLET_CONFIG = {
    "DEFAULT_CENTER": (52.1, 19.4),
    "DEFAULT_ZOOM": 6,
    "MIN_ZOOM": 3,
    "MAX_ZOOM": 18,
    "RESET_VIEW": False,
    # No OSM raster tiles — MapLibre style is attached in eurorace/static/eurorace/maplibre_admin.js
    "TILES": [],
    "PLUGINS": {
        "maplibre": {
            "css": [
                "https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.css",
            ],
            "js": [
                "https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.js",
                "https://unpkg.com/@maplibre/maplibre-gl-leaflet@0.0.22/leaflet-maplibre-gl.js",
                "eurorace/maplibre_admin.js",
            ],
            "auto-include": True,
        },
    },
}
